config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'articles', to: 'pages#articles'
  get 'projects', to: 'pages#projects'
  get 'music', to: 'pages#music'
  get 'books', to: 'pages#books'
  get 'infohub', to: 'pages#infohub'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def articles
  end

  def projects
  end

  def music
  end

  def books
  end

  def infohub
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,200&display=swap" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<!-- Navbar -->

<nav class="shift">
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <li>
      <%= link_to "Articles", articles_path %>
    </li>
    <li>
      <%= link_to "Projects", projects_path %>
    </li>
    <li>
      <%= link_to "Music", music_path %>
    </li>
    <li>
      <%= link_to "Books", books_path %>
    </li>
    <li>
      <%= link_to "Infohub", infohub_path %>
    </li>
    <li>
      <%= link_to "Contact", contact_path %>
    </li>
  </ul>
</nav>

<!-- Navbar -->

<div class="about-content-page">

  <div class="about-container">

    <h4>Louis Choo-Choy</h4>
    <h5>24/02/2001</h5>

  </div>

</div>

app/views/pages/articles.html.erb
<!-- Navbar -->

<nav class="shift">
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <li>
      <%= link_to "Articles", articles_path %>
    </li>
    <li>
      <%= link_to "Projects", projects_path %>
    </li>
    <li>
      <%= link_to "Music", music_path %>
    </li>
    <li>
      <%= link_to "Books", books_path %>
    </li>
    <li>
      <%= link_to "Infohub", infohub_path %>
    </li>
    <li>
      <%= link_to "Contact", contact_path %>
    </li>
  </ul>
</nav>

<!-- Navbar -->

<div class="articles-content-page">

  <div class="articles-container"></div>

</div>

app/views/pages/books.html.erb
<!-- Navbar -->

<nav class="shift">
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <li>
      <%= link_to "Articles", articles_path %>
    </li>
    <li>
      <%= link_to "Projects", projects_path %>
    </li>
    <li>
      <%= link_to "Music", music_path %>
    </li>
    <li>
      <%= link_to "Books", books_path %>
    </li>
    <li>
      <%= link_to "Infohub", infohub_path %>
    </li>
    <li>
      <%= link_to "Contact", contact_path %>
    </li>
  </ul>
</nav>

<!-- Navbar -->

<div class="books-content-page">

  <div class="books-container">

    <h4>Eichmann in Jerusalem</h4>

  </div>

</div>

app/views/pages/contact.html.erb
<!-- Navbar -->

<nav class="shift">
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <li>
      <%= link_to "Articles", articles_path %>
    </li>
    <li>
      <%= link_to "Projects", projects_path %>
    </li>
    <li>
      <%= link_to "Music", music_path %>
    </li>
    <li>
      <%= link_to "Books", books_path %>
    </li>
    <li>
      <%= link_to "Infohub", infohub_path %>
    </li>
    <li>
      <%= link_to "Contact", contact_path %>
    </li>
  </ul>
</nav>

<!-- Navbar -->

<div class="contact-content-page">

  <div class="contact-container">

    <h4>Find Me At</h4>

  </div>

</div>

app/views/pages/home.html.erb
<div class="whole-page">

  <!-- <img src="https://image.architonic.com/pro2-3/20083830/19501-a-faint-blush-19501-01-pro-b-arcit18.jpg" /> -->

  <div class="home-content-page">

    <script type="text/javascript" src="//use.typekit.net/qqh1pgl.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <h1>
      Louis Choo-Choy
    </h1>

    <div class="wrapper">
      <div class="features">

        <article>
          <%= link_to infohub_path, :style=>'text-decoration: none; color: white;' do %>
            <h3>InfoHub</h3>
            <p class="meta">
            </p>
            <div class="thumbnail" style="background-image: url(https://cdn.pixabay.com/photo/2016/11/06/10/38/old-1802683_1280.jpg);"></div>
          <% end %>
        </article>

        <article>
          <%= link_to about_path, :style=>'text-decoration: none; color: white;' do %>
            <h3>About</h3>
            <p class="meta">
            </p>
            <div class="thumbnail" style="background-image: url(https://cdn.pixabay.com/photo/2014/11/19/23/39/paris-538445_1280.jpg);"></div>
          <% end %>
        </article>

        <article>
          <%= link_to articles_path, :style=>'text-decoration: none; color: white;' do %>
            <h3>Articles</h3>
            <p class="meta">
            </p>
            <div class="thumbnail" style="background-image: url(https://cdn.pixabay.com/photo/2020/03/23/16/45/compass-4961383_1280.jpg);"></div>
          <% end %>
        </article>

        <article>
          <%= link_to projects_path, :style=>'text-decoration: none; color: white;' do %>
            <h3>Projects</h3>
            <p class="meta">
            </p>
            <div class="thumbnail" style="background-image: url(https://cdn.pixabay.com/photo/2018/05/13/18/59/steam-locomotive-3397463_1280.jpg);"></div>
          <% end %>
        </article>

        <article>
          <%= link_to music_path, :style=>'text-decoration: none; color: white;' do %>
            <h3>Music</h3>
            <p class="meta">
            </p>
            <div class="thumbnail" style="background-image: url(https://cdn.pixabay.com/photo/2018/05/17/15/24/armillar-ball-3408811_1280.jpg);"></div>
          <% end %>
        </article>

        <article>
          <%= link_to books_path, :style=>'text-decoration: none; color: white;' do %>
            <h3>Books</h3>
            <p class="meta">
            </p>
            <div class="thumbnail" style="background-image: url(https://cdn.pixabay.com/photo/2016/09/16/21/46/background-1675212_1280.jpg);"></div>
          <% end %>
        </article>

        <article>
          <%= link_to contact_path, :style=>'text-decoration: none; color: white;' do %>
            <h3>Contact</h3>
            <p class="meta">
            </p>
            <div class="thumbnail" style="background-image: url(https://cdn.pixabay.com/photo/2018/03/18/08/05/auto-3236000_1280.jpg);"></div>
          <% end %>
        </article>

      </div>
    </div>

  </div>

</div>

<script src='application.js'></script>

app/views/pages/infohub.html.erb
<!-- Navbar -->

<nav class="shift">
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <li>
      <%= link_to "Articles", articles_path %>
    </li>
    <li>
      <%= link_to "Projects", projects_path %>
    </li>
    <li>
      <%= link_to "Music", music_path %>
    </li>
    <li>
      <%= link_to "Books", books_path %>
    </li>
    <li>
      <%= link_to "Infohub", infohub_path %>
    </li>
    <li>
      <%= link_to "Contact", contact_path %>
    </li>
  </ul>
</nav>

<!-- Navbar -->

<div class="infohub-content-page">

  <div class="infohub-container">
    Packaged Information:
    Slatestarcodex
    Gwern
    WaitButWhy
    Farnham Street
    LessWrong
    Overcoming Bias
  </div>

</div>

app/views/pages/music.html.erb
<!-- Navbar -->

<nav class="shift">
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <li>
      <%= link_to "Articles", articles_path %>
    </li>
    <li>
      <%= link_to "Projects", projects_path %>
    </li>
    <li>
      <%= link_to "Music", music_path %>
    </li>
    <li>
      <%= link_to "Books", books_path %>
    </li>
    <li>
      <%= link_to "Infohub", infohub_path %>
    </li>
    <li>
      <%= link_to "Contact", contact_path %>
    </li>
  </ul>
</nav>

<!-- Navbar -->

<div class="music-content-page">

  <div class="music-container"></div>

</div>

app/views/pages/projects.html.erb
<!-- Navbar -->

<nav class="shift">
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <li>
      <%= link_to "Articles", articles_path %>
    </li>
    <li>
      <%= link_to "Projects", projects_path %>
    </li>
    <li>
      <%= link_to "Music", music_path %>
    </li>
    <li>
      <%= link_to "Books", books_path %>
    </li>
    <li>
      <%= link_to "Infohub", infohub_path %>
    </li>
    <li>
      <%= link_to "Contact", contact_path %>
    </li>
  </ul>
</nav>

<!-- Navbar -->

<div class="projects-content-page">

  <div class="projects-container"></div>

</div>